import os
import pytest
import tempfile
from app.services import geometry_service

def test_box_generation_and_export():
    """
    Golden STEP / Incremental B-Rep Test
    Tests whether the pythonocc-core backend can successfully:
    1. Parse a feature tree and generate B-Rep geometry and mesh data.
    2. Export the generated B-Rep to a valid STEP file.
    """
    
    # 1. Define a mock feature tree with a single Box
    features = [
        {
            "id": "test_box_1",
            "type": "BOX",
            "parameters": {
                "width": 10.0,
                "height": 20.0,
                "depth": 30.0,
                "x": 0.0,
                "y": 0.0,
                "z": 0.0
            }
        }
    ]
    
    # 2. Test B-Rep / Mesh Generation (Incremental B-Rep)
    result = geometry_service.process_features_cached(
        features,
        deflection=0.1,
        from_feature_index=0,
        feature_fingerprint="test_golden_hash"
    )
    
    assert result is not None, "Geometry processing should return a result."
    assert "data" in result, "Result must contain 'data' dictionary."
    assert "positions" in result["data"], "Result mesh must contain 'positions'."
    
    # The box should have vertices generated by the OCC mesher
    positions = result["data"]["positions"]
    assert len(positions) > 0, "OCC mesher failed to generate vertices for the box."
    
    # 3. Test Golden STEP Export
    with tempfile.TemporaryDirectory() as tmpdir:
        export_path = os.path.join(tmpdir, "golden_box.step")
        
        # Export the features to STEP format
        success = geometry_service.export_cad(features, "STEP", export_path)
        
        assert success is True, "Export to STEP should return True."
        assert os.path.exists(export_path), "STEP file should be created on disk."
        
        file_size = os.path.getsize(export_path)
        assert file_size > 0, "Exported STEP file should not be empty."
        
        # Verify STEP file signature
        with open(export_path, "r") as f:
            header = f.read(512)
            assert "ISO-10303-21;" in header, "File does not appear to be a valid STEP file."
