import os
import subprocess
import datetime
import sys

def run_cmd(cmd):
    try:
        return subprocess.check_output(cmd, shell=True, encoding="utf-8", stderr=subprocess.STDOUT).strip()
    except subprocess.CalledProcessError as e:
        return f"Error: {e.output}"

def generate_handover():
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # 1. Git Status
    git_status = run_cmd("git status --short")
    if not git_status:
        git_status = "No uncommitted changes."

    # 2. Last 30 lines of DEV_LOG.md
    dev_log = ""
    try:
        with open("DEV_LOG.md", "r", encoding="utf-8") as f:
            lines = f.readlines()
            dev_log = "".join(lines[-30:])
    except Exception as e:
        dev_log = f"Could not read DEV_LOG.md: {e}"

    # 3. Last Git Commit
    last_commit = run_cmd("git log -1 --oneline")

    handover_content = f"""# Handover Resume Guide (Auto-Generated)
**Last Saved:** {now}

> [!IMPORTANT]
> **To the next Agent/Human taking over:** 
> Please read this document entirely before starting work. It contains the exact state of the workspace at the moment the previous session was paused/interrupted.

## 1. Current Git State
```shell
{last_commit}
```

### Uncommitted Changes
```shell
{git_status}
```

## 2. Recent Development Log (DEV_LOG.md snippet)
```markdown
{dev_log}
```

## 3. Immediate Next Steps
Check the current `task.md` or `.gemini/antigravity-ide/brain/*/task.md` (if running inside Antigravity Sandbox) to see the exact checkboxes left pending.
Review `implementation_plan.md` in the current working directory or IDE sandbox to understand the architecture.

## 4. How to Resume
1. Address any `M` (Modified) or `??` (Untracked) files listed above.
2. If `DEV_LOG.md` mentions a failed test or bug, start your session by investigating that bug.
3. Once unblocked, continue following the PDCA closed loop defined in `GEMINI.md`.

---
*Generated by tools/save_checkpoint.py*
"""

    try:
        with open("handover_resume_guide.md", "w", encoding="utf-8") as f:
            f.write(handover_content)
        print(f"[SUCCESS] Handover checkpoint saved to handover_resume_guide.md at {now}")
    except Exception as e:
        print(f"[ERROR] Failed to write handover guide: {e}")
        sys.exit(1)

if __name__ == "__main__":
    generate_handover()
